list='gsjshajskdudbsjakahdhakdbxbjskabdkdlanagakdhshjllhduxkabakdlshabdkslabshxkalabdhdudnsgajkdhsbshsjakxbzjajkdbsjakdksbajaldhfydhcrjslaiqojsbs'
a='gsjshajskdudbsjakahdhakdbxbjskabdkdlanagakdhshjllhduxkabakdlshabdkslabshxkalabdhdudnsgajkdhsbshsjakxbzjajkdbsjakdksbajaldhfydhcrjslaiqojsbs'[::-1]
print(a)
#for i in ((list)):
   # print(i)